PREFIX jolux: <http://data.legilux.public.lu/resource/ontology/jolux#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT ?languageCode ?effectiveDate ?srNumber ?title ?abstract WHERE {
  VALUES (?languageCode ?language) {
    ("de" <http://publications.europa.eu/resource/authority/language/DEU>)
    ("fr" <http://publications.europa.eu/resource/authority/language/FRA>)
    ("it" <http://publications.europa.eu/resource/authority/language/ITA>)
  }

  ?consolidation jolux:isMemberOf ?abstract ;
                 jolux:dateApplicability ?effectiveDate .

  FILTER(
    xsd:date(?effectiveDate) >= "{{START_DATE}}"^^xsd:date &&
    xsd:date(?effectiveDate) <= "{{END_DATE}}"^^xsd:date
  )

  ?abstract jolux:classifiedByTaxonomyEntry ?taxonomyEntry ;
            jolux:isRealizedBy ?expression .
  ?taxonomyEntry skos:notation ?srNumber .
  ?expression jolux:language ?language ;
              jolux:title ?title .
}
ORDER BY ?languageCode ?effectiveDate ?srNumber ?abstract
